version: '3.1'
services:
  postgres:
    image: postgres:13.7-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"

  dache:
    build: .
    environment:
      LOGGING_REDACT_KEYS: false
      DURABILITY_ENGINE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: database
    ports:
      - "8080:8080"
