version: '3.1'
services:
  dache:
    build: .
    environment:
      DURABILITY_ENGINE: memory
      PORT: 8080
    ports:
      - "8080:8080"
  postgres:
    image: postgres:13.7-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
